name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: "11.24.0"

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "24.19.0"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Deploy to Server via rsync
        uses: easingthemes/ssh-deploy@v6
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete --delay-updates"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: ${{ secrets.WORKING_DIRECTORY }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
